# ============================================
# SonarQube Scanner - Configuración Global
# ============================================

# URL del servidor SonarQube
sonar.host.url=http://sonarqube:9000

# Encoding
sonar.sourceEncoding=UTF-8
